---

- name: rnasik-rest
  hosts: all 

  vars_files:
    - env_vars/base.yml
    - env_vars/{{ env }}.yml
    
  roles:
    - flask
    
  tags:
    - rest

- name: rnasik
  hosts: all 
    
  roles:
    - rnasik-pipe
    
  tags:
    - cmd