---
- file: path="{{ source_dir }}" state=directory mode=0755

- name: Download STAR
  get_url:
    url=https://github.com/alexdobin/STAR/archive/STAR_{{version}}.tar.gz
    dest={{source_dir}}/STAR-{{version}}.tar.gz

- name: Uncompress STAR
  unarchive: 
    src={{ source_dir }}/STAR-{{version}}.tar.gz
    dest={{ soft_dir }}
    copy=no
    creates={{ soft_dir }}/STAR-STAR_{{version}}/bin/Linux_x86_64_static/STARlong
    
- copy: src={{ soft_dir }}/STAR-STAR_{{version}}/bin/Linux_x86_64_static/STARlong dest={{ soft_dir }}/STAR-STAR_{{version}}/bin/STAR
- file: path={{ soft_dir }}/STAR-STAR_{{version}}/bin/STAR mode=0755

- name: add {{extra_path}} to path
  lineinfile: >
    dest=/etc/environment
    state=present
    backrefs=yes
    regexp='PATH=(["]*)((?!.*?{{extra_path}}).*?)(["]*)$'
    line="PATH=\1\2:{{extra_path}}\3"