version: "1.1"

app_user: root

# The directory to keep application source code.
app_directory: "/home/{{ app_user }}"

source_dir: "{{ app_directory }}/source"
soft_dir: "{{ app_directory }}/rnasik-pipe-{{version}}"

extra_path: "{{soft_dir}}/src"